dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh | bash
notifications:
  slack:
    rooms:
      secure: "3k+5UbLs2fSI8QRBEkKw4xEpRcv3b5d6Tqtt+Wr3B9NeZfQEAp3u07ulzX0oXKXrD/1BNdMfqC7R4OBQoDObKodcXTeq1CHuBAcfsQin9tq3D4NnSJBK5XZfohCH4OuGKezRqfD7pJ/ir7lTP0qOJqsfh6uLd6bAq9dFwxQW89DP8+A2vftl4vljUe03wykcsZ4059WYmTzi0zFw0u3uGZ3cyR5DtgRQ2Ucudru3vdYXrf0XAL/SKAyj3EW+1iWh2G7gVmsgom6TS0sK6aapQhDRHet5D4xVgNhvoIXGsF2CERQyauzUO1csJ9KhgKgR+eVkw7L5ANQ1zO71a5Cm/VKZQxSbEj+0w9amk1dLGkpfZD3xr2fiY6HnbK/+KIZ+qG2cTxpvfNynTQarS06+lBfuAHO4WthOr6g5EYS0c5Svi6X1DYM/MGsA3o9RPDFAgM1Gz+m9YZxgWgKBRlRayBzyH9J+wenqU4pQxpUN0/R64Ih4wGWOz93mhZXrwzkRSG6QEEQbI/CP1if8isPO0KHjysAJ1Ph/sRB7tkKkVVZiUA1rSl3v0BTRZBp7bGk/+VKH8kHgqMAK3MF4fmb5MR0gKuDzGKTZDEsDB6Ai7GzRHjs4rLLvWBaM5BXjeOVd6iEkJnjNNcAb7tMqWZ151oIU1DkRuUpqGkdFNsmLiZk="