dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh | bash
notifications:
  slack:
    rooms:
      secure:
iC1VQlr370ezAST+mEuvcND6mqFFwo+r9EdY6udtlIqS5+TR9nK+FeQp4kSqztKREQ7neJS3cqNqe6WhK7S4qZROa0rSnqW8d1t36w0KZmoV+68E2ouxzNgPww9Ld1OlCyTDl62FZajtYUkTV/34YPg3zXZ1grT7mrL0yq0/IpgoMMvQWra9jkPJI9yWeq8BTJexODwSVKOQFnBhB/afJCN/nIFv7ecUnEj671PmTnHwNeUOdNRNrTItnDzP+u+9FPcBj/zEl2NdVk9b41IEPhL4oIAEPL3cXcmebvajQsMhilnFOGpEhfKWJ3Pt4P46WdqVzCmwy8GF1Dix4VEG0/W7IiULVOQYFchMqdE4r1QgOaL3aAP0LXSrvP3fapIHY+UcGGNIT0CO5iJh7GPHMe5UkSrGqsrwvGLevxFbYuNUCUeVgHTodyTGagLb5u2kivE1G9LKxgdUVqwIV6TAlz+/Up//K8muD+3vHteMiH9nEEt2R141kx2zeQE2QmDL6lwMQvBQLo/Qzp8Pgr9g3O+Jd3/etYTfXvbStZNYQqOaKsdKRJg9kjX7vRemUV+z8ii5x3WCJ8ddnZ8LWamZQnzB8/nXW78uc5Sneu9lkdUCeVXvVxOQgmj3NZklbqNuF5JTE6CHMzlc9YmqDTUPCCL6LzPTJYgPiDkx3VpNz5M=
